api/devices/config/routes.json, api/devices/controllers/devices.js, api/devices/documentation/1.0.0/devices.json, api/devices/models/devices.js, api/devices/models/devices.settings.json, api/devices/services/devices.js, api/notificacoes/config/routes.json, api/notificacoes/controllers/notificacoes.js, api/notificacoes/documentation/1.0.0/notificacoes.json, api/notificacoes/models/notificacoes.js, api/notificacoes/models/notificacoes.settings.json, api/notificacoes/services/notificacoes.js, api/notificacoes/services/sendNotificationsExpo.js, extensions/documentation/documentation/1.0.0/full_documentation.json, package.json, yarn.lock
Criação das tabelas e serviços relacionados ao envio de notificações.
resolve #6
=> Serviço de notificações

auto-config.env, automate-script.sh, automate.py
=> Automate deploy

src/api/loja/content-types/loja/schema.json, src/api/produto-avulso/content-types/produto-avulso/schema.json, src/api/produto-avulso/controllers/produto-avulso.js, src/api/produto-avulso/routes/produto-avulso.js, src/api/produto-avulso/services/produto-avulso.js
Mantém o funcionamento do gerenciamento de produtos avulsos que uma CSA pode ter no AgroMart. Isso incluí criar, editar e excluir produtos avulsos de uma loja.
Closes #33
=> [33] gerenciar produtos avulsos

src/api/assinante/content-types/assinante/schema.json, src/api/assinante/controllers/assinante.js, src/api/assinante/routes/assinante.js, src/api/assinante/services/assinante.js, src/api/loja/content-types/loja/schema.json, src/api/plano/content-types/plano/schema.json, src/api/plano/controllers/plano.js, src/api/plano/routes/plano.js, src/api/plano/services/plano.js
Mantém o funcionamento do gerenciamento de planos que uma CSA pode ter no AgroMart. Isso incluí criar, editar e excluir planos e assinantes de uma loja.
Closes #35
=> [35] Gerenciar planos

src/api/cesta/content-types/cesta/schema.json, src/api/cesta/controllers/cesta.js, src/api/cesta/routes/cesta.js, src/api/cesta/services/cesta.js, src/api/loja/content-types/loja/schema.json
Mantém o funcionamento do gerenciamento de cestas das CSA no AgroMart. Isso incluí criar, editar e excluir cestas de uma loja.
resolves #36
=> [36] Gera cestas

README.md, src/api/extrato/content-types/extrato/schema.json, src/api/extrato/controllers/extrato.js, src/api/extrato/routes/extrato.js, src/api/extrato/services/extrato.js
Mantém o funcionamento do gerenciamento de extratos que uma CSA pode ter no AgroMart. Isso incluí criar, editar e excluir extratos de um usuário e de uma loja.
Closes #43
=> [43] Gerenciar extratos

README.md, config.ini, config/middlewares.js, src/middlewares/apiPrefix.js, tests/devices/findUserExpoPushToken.js, tests/devices/update.js
Automatiza deploy no heroku usando arquivo executável em qualquer maquina windows, linux ou mac
=> [45] Automatizar deploy no heroku

tests/app.test.js, tests/auth/index.js, tests/auth/login.js, tests/auth/register.js
Cria teste de integração do path `auth`: `/auth/local/register` e `/auth/local`
=> [48] Teste de integração path `auth` 

src/api/assinante/content-types/assinante/schema.json, src/api/cesta/content-types/cesta/schema.json, src/api/endereco/content-types/endereco/schema.json, src/api/loja/content-types/loja/schema.json, src/api/loja/controllers/loja.js, src/api/plano/content-types/plano/schema.json, src/api/produto-avulso/content-types/produto-avulso/schema.json, src/extensions/users-permissions/content-types/user/schema.json, src/middlewares/defaultRoutes.js, tests/app.test.js, tests/assinantes/getAssinantes.js, tests/assinantes/register.js, tests/lojas/index.js
Cria teste de integração do path `lojas`
=> [54] Teste de integração path `lojas`

src/api/produto-avulso/content-types/produto-avulso/schema.json, src/index.js, tests/app.test.js, tests/devices/update.js, tests/produtos-avulsos/index.js
Cria teste de integração do path `produtos-avulsos`:  `/produtos-avulsos/id`
=> [56] Teste de integração path `produtos-avulsos`

src/index.js, tests/app.test.js, tests/cestas/index.js
Cria teste de integração do path `cestas`: `cestas/id`
=> [58] Teste de integração path `cestas`

tests/app.test.js, tests/planos/index.js
Cria teste de integração do path `planos` : `planos/id`
=> [60] Teste de integração path `planos`

src/api/extrato/content-types/extrato/schema.json, src/index.js, tests/app.test.js, tests/extratoes/index.js
Cria teste de integração do path `extratoes`:  `extratoes`
=> [62] adiciona teste de integração path `extrato`

src/api/extrato/controllers/extrato.js, src/middlewares/helpers/transformObject.js, tests/extratoes/index.js, tests/lojas/index.js
Cria teste de integração do path `extratoes`:  `extratoes?id`
=> [62] adiciona teste de integração path extrato

package.json, src/api/notificacao/controllers/notificacao.js, src/api/notificacao/routes/notificacao.js, src/api/notificacao/services/notificacao.js, src/index.js, tests/app.test.js, tests/extratoes/index.js, tests/helpers/strapi.js, tests/notificacoes/index.js, tests/planos/index.js, yarn.lock
Cria teste de integração do path `notificacoes`: `notificacoes`
=> [66] Teste de integração path `notificacoes`

config/database.js
Alterando configuração para certificados do banco de dados.
=> [Hotfix] database ssl

config.ini, config/database.js
=> Deploy - ajustes na database

src/plugins/pagamento/README.md
Adiciona a documentação para o plugin de pagamento.
=> Inicia Documentacao

README.md, src/plugins/pagamento/admin/src/components/GatewayCustom/index.css, src/plugins/pagamento/admin/src/components/GatewayCustom/index.js, src/plugins/pagamento/server/utils/gateways/padrao.js, tests/app.test.js, tests/gateway/create.js, tests/pagamento/create.js
Ajusta frontend do gateway generico
=> [Hotfix] Ajuste no frontend dos campos de gateway generico

src/plugins/pagamento/admin/src/components/GatewayCustom/index.js, src/plugins/pagamento/server/controllers/pagamento/index.js, src/plugins/pagamento/server/utils/gateways/mercadoPago.js, src/plugins/pagamento/server/utils/gateways/padrao.js
Atualiza front p/ poder gerar link dentro do Heroku
=> Atualização do front p/ deploy

auto-config.txt, config/database.js, src/api/assinante/controllers/assinante.js, src/api/devices/controllers/devices.js, src/api/loja/controllers/loja.js, src/api/produto-avulso/content-types/produto-avulso/schema.json
Unificação das Branches e Correção na exibição de imagens de cestas e produtos na API
=> TCC Christian Thiago
